### ISSUE TITLE
No Intro

### ISSUE THREAD

**Issue by Handyfon** [arcanistzed/scs#1]
Foundry 0.8.8.
The intro doesn't pop up.
Additionally it seems the intro breaks new worlds that don't scene yet. (The world becomes unresponsive, likely some sort of infinity loop)
![image](https://user-images.githubusercontent.com/28778881/125602448-f45a8293-7d75-42b4-a733-50f49a006ba6.png)
![image](https://user-images.githubusercontent.com/28778881/125602494-3d9f3c94-a529-40b6-a6a3-5f900d3c96ed.png)

**Comment by arcanistzed** [comment]
You're using an outdated version of IntroJS, but even the latest version won't work because it doesn't include any of the library's css files :facepalm: 
It will work if installed from here https://github.com/arcanistzed/intro.js-lib/releases/download/3.2.1-fvtt3/module.json

**Comment by baileywick** [comment]
I've installed from the link you provided here and still can't get the tutorial to show up. Would love to explore how to use this system.

**Comment by arcanistzed** [comment]
@baileywick Do you see any errors in the console? (press F12 to open)
Keep in mind that if you've clicked "Don't Show Again", you must re-enable the tutorial in settings.

**Comment by baileywick** [comment]
No console errors. Does it only work with browser and not the Foundry
client? Or just for the player and not the GM?

**Comment by arcanistzed** [comment]
It works for both players and the GM. The tutorial doesn't differentiate
between them.

I've only tested it in the browser. I don't have an installation with the
client, but I can get one and test later. I think Corporat had success with
using it in the client on his Twitch stream yesterday, so that shouldn't be
an issue either.

Does it work in the browser?

**Comment by baileywick** [comment]
I've tried browser and client. Doesn't work with either. I've also disabled
all other modules. No console errors. Still doesn't work. I see the little
UI in the corner, but all I can do is forward or reverse it. Not sure if
that's the extent of the functionality.

**Comment by arcanistzed** [comment]
Can you confirm that you are on IntroJS `3.2.1-fvtt3` and SCS `1.0.2`?

**Comment by arcanistzed** [comment]
@baileywick Did you figure this out?

**Comment by baileywick** [comment]
Intro.js is v3.2.1-vtt3. not 2.3.1. is that what you mean?

Still not working. Want to ping me on discord?

**Comment by arcanistzed** [comment]
Yes, that's what I meant,
We should indeed move this to discord. I made a new server for my modules https://discord.gg/AAkZWWqVav
I'll see you there :slightly_smiling_face:

**Comment by arcanistzed** [comment]
Fixed by https://github.com/League-of-Foundry-Developers/intro.js-lib/pull/5
