### ISSUE TITLE
[BUG] 2.9.0 Action Locking Broken

### ISSUE THREAD

**Issue by DM-miX** [arcanistzed/scs#10]
**Describe the bug**
Action Locking no longer works

**To Reproduce**
Enable action locking
Set Round to 1 or greater
Also tried adding the combants to the combat tracker

**Foundry VTT version:**
Ex: 0.8.9

**Additional**
if there is no encounter in the combat tracker, when moving from round 0 to round 1 does not start an encounter.

**Comment by arcanistzed** [comment]
Can you elaborate on this issue? Did anything change in your setup for this to stop working? The additional thing is fixed in the next release.

**Comment by arcanistzed** [comment]
Can you elaborate on this issue? Did anything change in your setup for this to stop working? The additional thing is fixed in the next release.

**Comment by DM-miX** [comment]
Nothing changed in my setup… module updates…
Mmm - pretty sure I tried with all other modules off though, will try again

but to elaborate - with action locking on, there are warnings and users are free to take actions in the move section, or move when it’s time for actions

**Comment by arcanistzed** [comment]
Could you confirm that you have Action Locking enabled?

**Comment by DM-miX** [comment]
Yeah sure is. Have just checked again with only SCS enabled and same issue occurs

**Comment by arcanistzed** [comment]
Sorry for the long wait. I haven't been able to reproduce this issue at all, so I can't fix it. I could join your game to see the issue myself if you'd like. If not, I'll have to close the issue 🙂
