### ISSUE TITLE
Move up when SmallTime date is visible

### ISSUE THREAD

**Issue by Baxmann** [arcanistzed/scs#11]
This is a little bit of a nitpick, but by clicking the Clock on SmallTime, it can also show the In-Universe Date. The catch is that it makes SmallTime bigger, which causes SCS to overlap with SmallTime.
![Clipping](https://user-images.githubusercontent.com/34702584/138572970-994f498d-cf4e-43d7-ab9e-0d78592da3b0.png)

**Comment by arcanistzed** [comment]
Fixed 0d507b49f32e2d29c816d774210a990de95744a1
