### ISSUE TITLE
[BUG] A few issues (summary)

### ISSUE THREAD

**Issue by DM-miX** [arcanistzed/scs#12]
Hi Arc
Sorry for the 'summary' - I've ran up [a video of some of the issues](https://drive.google.com/file/d/1-3ocSTy0q04yv1bPgj7sdV5UDCKWM0_K/view?usp=sharing)

Only 4 modules activated. SCS, intro.js, Better Rolls and libwrapper.
SCS 2.9.0
Better Rolls 1.6.14

Foundy 0.8.9
dnd5e 1.5.3

Happy to tee up a time you can jump onto my server if it helps, I could even set up a dummy world and leave that running so you can jump in when you're ready.

### 1. There’s a few problems with the combat tracker integration . #6 
- Adding combatants throws SCS error: Current round doesn’t match core. (This is in the video)
- Changing rounds in tracker doesn’t update SCS window (In the vid it jumps from 0 to 2)
- Changing SCS round without Combatants added to encounter throws core warning - There are no combatants remains which are not defeated
- From Round 0, clicking the next round button doesn’t start an encounter if there is no No Active Encounter
- (Last 2 not in video)

### 2. (from 34 sec) Tokens can move freely with Action Locking On:  
- You can see Action Locking is on as I try to attack while in the move cycle.
But I can move the token freely when in attack and magic cycles.
(I tested this ages ago, several times to be sure! but it looks like Action Locking is at least partially working, unlike with #10  )

### 3. (from 46 sec) Better Rolls Issue #8 
- I Roll an attack using Better Rolls. The hud token appears on the players screen, but not the DM’s. Vice versa when I roll for a player on the DM screen, the player cannot see the hud token.
When using core rolls hud token works as expected.

### 4. (from 1 min 40 sec) Disable SCS outside of combat #9 
- Outside of combat my the Cleric can’t attack or cast detect thoughts without the appropriate cycle mode being set.

**Comment by arcanistzed** [comment]
Thanks so much for this!
2 would be a feature request as Action Locking currently only affects actions/features and doesn't do anything to movement.
4 I can easily fix.
3 and 1 are issues I haven't yet reproduced myself.

I'll look into all this

**Comment by arcanistzed** [comment]
I'm re-watching your video and it seems that the Better Rolls chat card is different for the one rolling the attack vs everyone else. Maybe there is a Better Rolls setting that does this?
FYI the Attack Roll HUD feature works by looking at the chat cards, so if the messages are significantly different, I need to implement a seperate workflow. This is why there is different logic for the core chat cards vs the BetterRolls ones. I didn't realize BetterRolls would have different chat card options, but this is likely the issue.

**Comment by DM-miX** [comment]
Ah all good on 2 then, not a big deal, just noticed while I was in QA mode :D

I changed the better rolls card a little so that it auto rolls damage and doesn't show the damage button rolled character action from each side.
It looks like an exact match in both windows. Maybe something in the card object that's not shown??

![ScreenShot 1](https://user-images.githubusercontent.com/72422516/138625359-de738fa2-7ae0-446c-b416-6628bb02c1dd.png)

**Comment by Lethay** [comment]
I discovered that if automatic rolling of damage is disabled and the DM clicks the button to roll damage, _then_ they get to see the attack roll above player's tokens. But that's obviously not ideal.
However, this is likely just related to the original problem of the DM only being able to see icons for tokens that they personally roll for.

**Comment by Lethay** [comment]
I couldn't find any combination of settings for Better Rolls that make the icons appear for the GM when someone else rolls. What combination did you use, @arcanistzed ? Hunting through the chat for rolls is a bit of a bother and I'd like to fix this, but not enough to drop Better Rolls.

**Comment by arcanistzed** [comment]
I used the default settings in all my testing.

To be honest I've lost track of this ticket a bit...
If you don't mind, I would prefer if the issues were reposted separately, so I can deal with them individually.

**Comment by arcanistzed** [comment]
I'm closing this issue and reopen #8
