### ISSUE TITLE
[FEAT] Make removal of turns from combat tracker a toggleable option

### ISSUE THREAD

**Issue by Lethay** [arcanistzed/scs#14]
I like to use the initiative tracker in addition to the simulatenous combat system. When the order of events is important, I like to use initiative instead of a dexterity check. When doing a chase scene, initative is still required to some degree, though I have some homebrew to make this somewhat simultaenous too.

Not having turns in the combat tracker makes this harder. Could this be made an option for the game master, instead of a forced modification to the UI?

**Comment by arcanistzed** [comment]
Makes sense. I'll add an option next time I take a look at this module

**Comment by Lethay** [comment]
Thank you 🙂.
