### ISSUE TITLE
Error with LibWrapper

### ISSUE THREAD

**Issue by NiceTSY** [arcanistzed/scs#2]
Hi,

I just came across an error in my world today, it is between the libWrapper module and SCS (see below image for the JS console).
My Foundry is updated to the latest 0.8 version and both modules are updated too. I tried with and without any other mods and the problem is present in both.

![image](https://user-images.githubusercontent.com/38940602/128489559-28cbdbcc-a994-4206-a459-ac2f465f284c.png)

**Comment by arcanistzed** [comment]
@NiceTSY What system are you using?

**Comment by NiceTSY** [comment]
I am using the latest Degenesis system by MooMan :)

**Comment by NiceTSY** [comment]
And it seems that your latest release fixes the issue as it is no more appearing! Many thanks @arcanistzed!

**Comment by arcanistzed** [comment]
Yeah, that's because I removed Action Locking for any system that isn't supported (currently only 5e is). It looks like I'll have to program it separately for each system.
