### ISSUE TITLE
[FEAT] Compatability with Better Rolls

### ISSUE THREAD

**Issue by DM-miX** [arcanistzed/scs#5]
Using Better Rolls the default roll is overridden by SCS.
If I bypass by clicking the Attack Roll button on the charatcer sheet, The Roll comes up as 0 on the characters token.

BTW - love this - thank you so much for all your work!

**Comment by DM-miX** [comment]
Sweeeeeet!!

**Comment by arcanistzed** [comment]
Yeah, it works pretty well except for the two things described in the README, but those should be mostly non-issues. Let me know if you have any other problems!
