### ISSUE TITLE
[FEAT] Combat tracker integration

### ISSUE THREAD

**Issue by dirkson** [arcanistzed/scs#6]
Many modules depend on the combat tracker for integration - Maestro for combat music, about time/simple calendar for time tracking, etc. 

Rather than trying to integrate them all, I think it might be better to have a way to begin/end foundry-combat built into SCS. This could be used to show/hide the SCS combat tracker as well, presenting a bit of a cleaner interface when not in combat. 

I imagine that, since we don't actually care about what actors are in the combat tracker, all in the active scene could be selected.

Thanks for making this thing, by the by. It's making our combats a lot smoother, especially when there are a lot of enemies involved.

Cheers!

**Comment by arcanistzed** [comment]
I think you're right that I should work on controlling the Combat Tracker behind the scenes for compatibility, although keep in mind that it's currently intended to be hidden while using the SCS (hence that being the default).

I don't know if I want to hide/show the SCS, because part of the idea with the system is that combat is less of a distinct thing from everything else. Maybe I'll look into adding an option, but it might require rewriting some stuff...

I also have plans to add some more integration with Combat Tracker Groups (my other combat module) which will mean having the Combat Tracker visible and useful.

Thanks for the feedback! I love to see people getting value out of my modules 😁

**Comment by dirkson** [comment]
I agree that hiding the Combat Tracker is a good default, even when integrating with it.

I don't think my group minds combat being a distinct 'thing' though, so our usage is a little different than yours.

That said, I imagine you could just tie the Combat Tracker state to 'round' if you wanted, and have anything other than 'round 0' mean that combat was on for the modules that care about that.

**Comment by arcanistzed** [comment]
That's already how it works. The Round is already synced to the Combat Tracker. Round 0 should already end combat.

**Comment by dirkson** [comment]
Oh, so it does! Did it always do that? 

Currently I have to select combatants to make that work though - It won't, say, auto-pull them all from the existing scene, or even just start combat sans-combatants.

**Comment by waterlava** [comment]
Yeah, it's always done that.
I don't think auto-adding everyone in the scene is a good idea and starting a combat without combatants is not possible.
You are expected to select combatants for other features as well such as the About Time integration.

**Comment by arcanistzed** [comment]
Yeah, it's always done that.
I don't think auto-adding everyone in the scene is a good idea and starting a combat without combatants is not possible.
You are expected to select combatants for other features as well such as the About Time integration.

**Comment by dirkson** [comment]
I can start the combat tracker manually without combatants. It complains about it, but it does seem to work.

So this is tricky. Remembering to add people to a non-existant combat tracker that you never use or see doesn't seem like a good interface. You don't like defaulting to adding everyone in the scene, probably for good reason. Maybe there could be a 'default' empty actor added to the scene if combat goes from 0 to 1 without anyone in the combat tracker?

**Comment by arcanistzed** [comment]
Ok, I was wrong about this. I will make it stop combat when round is equal to zero and then start it when the round goes to 1, regardless of whether there are any combatants.

**Comment by arcanistzed** [comment]
This is hopefully accomplished with the changes in [v2.9.0](https://github.com/arcanistzed/scs/releases/tag/2.9.0). Let me know if you have any questions!
